Repository everyone-s-garden/everyonesgarden-v2, pull requests merged in 2023-12, with the labels that each got.

#2 chore: 프로젝트 초기 설정
  .gitignore
  api/build.gradle
  api/gradle/wrapper/gradle-wrapper.jar
  api/gradle/wrapper/gradle-wrapper.properties
  api/src/main/java/com/garden/back/ApiApplication.java
  api/src/main/java/com/garden/back/health/healthChecker.java
  api/src/main/resources/application.properties
  api/src/test/java/com/garden/back/ApiApplicationTests.java
  batch/build.gradle
  batch/gradle/wrapper/gradle-wrapper.jar
  batch/gradle/wrapper/gradle-wrapper.properties
  batch/src/main/java/com/garden/back/BatchApplication.java
  batch/src/main/resources/application.properties
  batch/src/test/java/com/garden/back/BatchApplicationTests.java
  build.gradle
  core/build.gradle
  core/gradle/wrapper/gradle-wrapper.jar
  core/gradle/wrapper/gradle-wrapper.properties
  core/src/main/java/com/graden/back/CoreApplication.java
  core/src/main/resources/application.properties
  core/src/test/java/com/graden/back/CoreApplicationTests.java
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: chore

#9 Chore : build.gradle 설정
  .gitignore
  api/build.gradle
  api/src/main/resources/application.properties
  build.gradle
  core/build.gradle
Labels: chore

#32 regions srid 설정 쿼리 추가 및 Geometry관련 global 이동
  api/src/main/resources/db/migration/V202312230210__alter_regions.sql
  core/src/main/java/com/garden/back/garden/service/dto/request/GardenByComplexesParam.java
  core/src/main/java/com/garden/back/global/GeometryUtil.java
  core/src/test/java/com/garden/back/garden/model/GardenTest.java
  core/src/test/java/com/garden/back/garden/service/RandomPointGenerator.java
  core/src/test/java/com/garden/back/testutil/garden/GardenFixture.java
Labels: chore

#45 bug & feat : 텃밭 위치에 따른 조회 파싱 문제 해결 및 chat 모듈 설정, 도메인 구현
  README.md
  api/src/main/resources/db/migration/V202312180632__init.sql
  api/src/main/resources/db/migration/V202312210540__create_feedback.sql
  api/src/main/resources/db/migration/V202312221353__create_garden.sql
  api/src/main/resources/db/migration/V202312252158__create_members.sql
  api/src/main/resources/db/migration/Vgarden__init.sql
  build.gradle
  chat/build.gradle
  chat/src/main/java/com/graden/back/ChatApplication.java
  chat/src/main/java/com/graden/back/domain/ChatImage.java
  chat/src/main/java/com/graden/back/domain/ChatMessage.java
  chat/src/main/java/com/graden/back/domain/ChatRoom.java
  chat/src/main/java/com/graden/back/domain/ChatRoomInfo.java
  chat/src/main/java/com/graden/back/domain/ChatType.java
  chat/src/main/java/com/graden/back/domain/MessageType.java
  core/src/main/java/com/garden/back/garden/repository/garden/dto/GardensByComplexes.java
  core/src/test/java/com/garden/back/garden/domain/GardenImageTest.java
  core/src/test/java/com/garden/back/garden/domain/GardenLikeTest.java
  core/src/test/java/com/garden/back/garden/service/GardenCommandServiceTest.java
  core/src/test/java/com/garden/back/garden/service/GardenReadServiceTest.java
  core/src/test/java/com/garden/back/garden/service/recentview/RecentViewGardensTest.java
  img_1.png
  settings.gradle
Labels: bug, chore

#46 Release
  README.md
  api/src/main/resources/db/migration/V202312180632__init.sql
  api/src/main/resources/db/migration/V202312210540__create_feedback.sql
  api/src/main/resources/db/migration/V202312221353__create_garden.sql
  api/src/main/resources/db/migration/V202312252158__create_members.sql
  api/src/main/resources/db/migration/Vgarden__init.sql
  build.gradle
  chat/build.gradle
  chat/src/main/java/com/graden/back/ChatApplication.java
  chat/src/main/java/com/graden/back/domain/ChatImage.java
  chat/src/main/java/com/graden/back/domain/ChatMessage.java
  chat/src/main/java/com/graden/back/domain/ChatRoom.java
  chat/src/main/java/com/graden/back/domain/ChatRoomInfo.java
  chat/src/main/java/com/graden/back/domain/ChatType.java
  chat/src/main/java/com/graden/back/domain/MessageType.java
  core/src/main/java/com/garden/back/garden/repository/garden/dto/GardensByComplexes.java
  core/src/test/java/com/garden/back/garden/domain/GardenImageTest.java
  core/src/test/java/com/garden/back/garden/domain/GardenLikeTest.java
  core/src/test/java/com/garden/back/garden/service/GardenCommandServiceTest.java
  core/src/test/java/com/garden/back/garden/service/GardenReadServiceTest.java
  core/src/test/java/com/garden/back/garden/service/recentview/RecentViewGardensTest.java
  img_1.png
  settings.gradle
Labels: release
