Repository everyone-s-garden/everyonesgarden-v2, pull requests merged in 2024-01, with the labels that each got.

#52 fix : delete 관련 트랜잭션으로 묶기
  core/src/main/java/com/garden/back/garden/service/GardenCommandService.java
Labels: bug

#53 배포
  core/src/main/java/com/garden/back/garden/service/GardenCommandService.java
Labels: release

#56 refactor: 로그인시 응답으로 memberId 필드 추가
  api/src/main/java/com/garden/back/auth/jwt/TokenProvider.java
  api/src/main/java/com/garden/back/auth/jwt/response/TokenResponse.java
  api/src/test/java/com/garden/back/docs/auth/AuthRestDocs.java
Labels: refactor

#57 feat : 마이페이지 회원 정보 조회 기능 구현
  api/src/docs/asciidoc/index.asciidoc
  api/src/docs/asciidoc/mypage/mypage.adoc
  api/src/main/java/com/garden/back/auth/AuthService.java
  api/src/main/java/com/garden/back/member/MemberController.java
  api/src/main/java/com/garden/back/member/dto/MemberMyPageResponse.java
  api/src/test/java/com/garden/back/auth/AuthServiceTest.java
  api/src/test/java/com/garden/back/docs/member/MemberFixture.java
  api/src/test/java/com/garden/back/docs/member/MemberRestDocs.java
  core/src/main/java/com/garden/back/member/MemberRepository.java
  core/src/main/java/com/garden/back/member/repository/MemberRepository.java
  core/src/main/java/com/garden/back/member/repository/MyPageMemberRepositoryResponse.java
  core/src/main/java/com/garden/back/member/service/MemberService.java
  core/src/main/java/com/garden/back/member/service/dto/MemberMyPageResult.java
  core/src/test/java/com/garden/back/member/service/MemberServiceTest.java
  core/src/test/java/com/garden/back/post/service/PostQueryServiceTest.java
Labels: feat

#58 배포
  api/src/docs/asciidoc/index.asciidoc
  api/src/docs/asciidoc/mypage/mypage.adoc
  api/src/main/java/com/garden/back/auth/AuthService.java
  api/src/main/java/com/garden/back/auth/jwt/TokenProvider.java
  api/src/main/java/com/garden/back/auth/jwt/response/TokenResponse.java
  api/src/main/java/com/garden/back/member/MemberController.java
  api/src/main/java/com/garden/back/member/dto/MemberMyPageResponse.java
  api/src/test/java/com/garden/back/auth/AuthServiceTest.java
  api/src/test/java/com/garden/back/docs/auth/AuthRestDocs.java
  api/src/test/java/com/garden/back/docs/member/MemberFixture.java
  api/src/test/java/com/garden/back/docs/member/MemberRestDocs.java
  core/src/main/java/com/garden/back/member/MemberRepository.java
  core/src/main/java/com/garden/back/member/repository/MemberRepository.java
  core/src/main/java/com/garden/back/member/repository/MyPageMemberRepositoryResponse.java
  core/src/main/java/com/garden/back/member/service/MemberService.java
  core/src/main/java/com/garden/back/member/service/dto/MemberMyPageResult.java
  core/src/test/java/com/garden/back/member/service/MemberServiceTest.java
  core/src/test/java/com/garden/back/post/service/PostQueryServiceTest.java
Labels: release

#78 refactor : 텃밭 분양 정보 및 내가 가꾸는 텃밭 이미지 null 요청에 대한 방어 처리
  api/src/main/java/com/garden/back/garden/dto/request/GardenCreateRequest.java
  api/src/main/java/com/garden/back/garden/dto/request/GardenUpdateRequest.java
  api/src/main/resources/db/migration/V20240119__init.sql
  core/src/main/java/com/garden/back/garden/domain/MyManagedGarden.java
  core/src/main/java/com/garden/back/garden/service/GardenCommandService.java
  core/src/main/java/com/garden/back/garden/service/dto/request/MyManagedGardenCreateParam.java
  core/src/main/java/com/garden/back/global/image/NCPImageUploader.java
  core/src/main/java/com/garden/back/global/image/ParallelImageUploader.java
  core/src/test/java/com/garden/back/feedback/service/FeedbackServiceTest.java
  core/src/test/java/com/garden/back/garden/service/GardenCommandServiceTest.java
  core/src/test/java/com/garden/back/global/IntegrationTestSupport.java
  core/src/test/java/com/garden/back/testutil/garden/GardenFixture.java
Labels: refactor

#80 feat : 채팅방 목록 조회
  api/build.gradle
  api/src/docs/asciidoc/chat/chats.adoc
  api/src/main/java/com/garden/back/chat/gardenchat/controller/GardenChatController.java
  api/src/main/java/com/garden/back/chat/gardenchat/controller/dto/response/GardenChatRoomsFindResponses.java
  api/src/main/java/com/garden/back/chat/gardenchat/facade/ChatRoomFacade.java
  api/src/main/java/com/garden/back/chat/gardenchat/facade/GardenChatRoomsFindFacadeRequest.java
  api/src/main/java/com/garden/back/chat/gardenchat/facade/GardenChatRoomsFindFacadeResponses.java
  api/src/test/java/com/garden/back/controller/chat/ChatRoomFacadeTest.java
  api/src/test/java/com/garden/back/controller/chat/ChatRoomFixture.java
  api/src/test/java/com/garden/back/controller/chat/GardenChatRoomControllerTest.java
  api/src/test/java/com/garden/back/docs/chat/garden/ChatMessageDocsTest.java
  api/src/test/java/com/garden/back/docs/chat/global/ChatRoomFixture.java
  build.gradle
  chat/src/main/java/com/garden/back/crop/domain/CropChatRoom.java
  chat/src/main/java/com/garden/back/garden/repository/chatmessage/ChatRoomFindRepositoryResponse.java
  chat/src/main/java/com/garden/back/garden/repository/chatmessage/GardenChatMessageJpaRepository.java
  chat/src/main/java/com/garden/back/garden/repository/chatmessage/GardenChatMessageRepository.java
  chat/src/main/java/com/garden/back/garden/repository/chatmessage/GardenChatMessageRepositoryImpl.java
  chat/src/main/java/com/garden/back/garden/service/GardenChatRoomService.java
  chat/src/main/java/com/garden/back/garden/service/GardenChatService.java
  chat/src/main/java/com/garden/back/garden/service/dto/request/GardenChatRoomsFindParam.java
  chat/src/main/java/com/garden/back/garden/service/dto/response/GardenChatRoomsFindResults.java
  chat/src/main/java/com/garden/back/util/PageMaker.java
  chat/src/test/java/com/garden/back/garden/repository/chatentry/garden/GardenChatRoomRoomEntryLocalRepositoryTest.java
  chat/src/test/java/com/garden/back/service/ChatRoomFixture.java
  chat/src/test/java/com/garden/back/service/GardenChatServiceTest.java
  chat/src/test/java/com/garden/back/util/PageMakerTest.java
  core/src/main/java/com/garden/back/garden/repository/gardenimage/GardenImageJpaRepository.java
  core/src/main/java/com/garden/back/garden/repository/gardenimage/GardenImageRepository.java
  core/src/main/java/com/garden/back/garden/repository/gardenimage/GardenImageRepositoryImpl.java
  core/src/main/java/com/garden/back/garden/service/GardenReadService.java
  core/src/test/java/com/garden/back/garden/service/GardenReadServiceTest.java
Labels: feat

#82 배포
  api/build.gradle
  api/src/docs/asciidoc/chat/chats.adoc
  api/src/docs/asciidoc/crop/crops.adoc
  api/src/docs/asciidoc/report/reports.adoc
  api/src/main/java/com/garden/back/chat/gardenchat/controller/GardenChatController.java
  api/src/main/java/com/garden/back/chat/gardenchat/controller/dto/response/GardenChatRoomsFindResponses.java
  api/src/main/java/com/garden/back/chat/gardenchat/facade/ChatRoomFacade.java
  api/src/main/java/com/garden/back/chat/gardenchat/facade/GardenChatRoomsFindFacadeRequest.java
  api/src/main/java/com/garden/back/chat/gardenchat/facade/GardenChatRoomsFindFacadeResponses.java
  api/src/test/java/com/garden/back/controller/chat/ChatRoomFacadeTest.java
  api/src/test/java/com/garden/back/controller/chat/ChatRoomFixture.java
  api/src/test/java/com/garden/back/controller/chat/GardenChatRoomControllerTest.java
  api/src/test/java/com/garden/back/docs/chat/garden/ChatMessageDocsTest.java
  api/src/test/java/com/garden/back/docs/chat/global/ChatRoomFixture.java
  build.gradle
  chat/src/main/java/com/garden/back/crop/domain/CropChatRoom.java
  chat/src/main/java/com/garden/back/garden/repository/chatmessage/ChatRoomFindRepositoryResponse.java
  chat/src/main/java/com/garden/back/garden/repository/chatmessage/GardenChatMessageJpaRepository.java
  chat/src/main/java/com/garden/back/garden/repository/chatmessage/GardenChatMessageRepository.java
  chat/src/main/java/com/garden/back/garden/repository/chatmessage/GardenChatMessageRepositoryImpl.java
  chat/src/main/java/com/garden/back/garden/service/GardenChatRoomService.java
  chat/src/main/java/com/garden/back/garden/service/GardenChatService.java
  chat/src/main/java/com/garden/back/garden/service/dto/request/GardenChatRoomsFindParam.java
  chat/src/main/java/com/garden/back/garden/service/dto/response/GardenChatRoomsFindResults.java
  chat/src/main/java/com/garden/back/util/PageMaker.java
  chat/src/test/java/com/garden/back/garden/repository/chatentry/garden/GardenChatRoomRoomEntryLocalRepositoryTest.java
  chat/src/test/java/com/garden/back/service/ChatRoomFixture.java
  chat/src/test/java/com/garden/back/service/GardenChatServiceTest.java
  chat/src/test/java/com/garden/back/util/PageMakerTest.java
  core/src/main/java/com/garden/back/garden/repository/gardenimage/GardenImageJpaRepository.java
  core/src/main/java/com/garden/back/garden/repository/gardenimage/GardenImageRepository.java
  core/src/main/java/com/garden/back/garden/repository/gardenimage/GardenImageRepositoryImpl.java
  core/src/main/java/com/garden/back/garden/service/GardenReadService.java
  core/src/test/java/com/garden/back/garden/service/GardenReadServiceTest.java
Labels: release

#84 uncoverd test : chatType에 대한 테스트 구현
  chat/src/test/java/com/garden/back/global/ChatTypeTest.java
Labels: test

#85 배포
  chat/src/test/java/com/garden/back/global/ChatTypeTest.java
Labels: release

#86 feat : 로그인 상태 유지 변경 및 채팅방 목록 필요한 필드 추가
  api/src/main/java/com/garden/back/chat/gardenchat/controller/dto/response/GardenChatRoomsFindResponses.java
  api/src/main/java/com/garden/back/chat/gardenchat/facade/GardenChatRoomsFindFacadeResponses.java
  api/src/main/java/com/garden/back/garden/GardenController.java
  api/src/test/java/com/garden/back/docs/chat/garden/ChatMessageDocsTest.java
  api/src/test/java/com/garden/back/docs/chat/global/ChatRoomFixture.java
Labels: enhancement

#87 배포
  api/src/main/java/com/garden/back/chat/gardenchat/controller/dto/response/GardenChatRoomsFindResponses.java
  api/src/main/java/com/garden/back/chat/gardenchat/facade/GardenChatRoomsFindFacadeResponses.java
  api/src/main/java/com/garden/back/garden/GardenController.java
  api/src/test/java/com/garden/back/docs/chat/garden/ChatMessageDocsTest.java
  api/src/test/java/com/garden/back/docs/chat/global/ChatRoomFixture.java
Labels: release

#88 feat: 약속잡기 기능 추가
  api/src/docs/asciidoc/appointment/appointment.adoc
  api/src/docs/asciidoc/crop/crops.adoc
  api/src/docs/asciidoc/index.asciidoc
  api/src/main/java/com/garden/back/appointment/AppointmentController.java
  api/src/main/java/com/garden/back/appointment/request/AppointRequest.java
  api/src/main/java/com/garden/back/auth/config/SecurityConfig.java
  api/src/main/java/com/garden/back/crop/CropController.java
  api/src/main/java/com/garden/back/crop/MyCropController.java
  api/src/test/java/com/garden/back/ControllerTestSupport.java
  api/src/test/java/com/garden/back/docs/appointment/AppointmentRestDocs.java
  api/src/test/java/com/garden/back/docs/crop/CropRestDocs.java
  api/src/test/java/com/garden/back/docs/crop/MyCropRestDocs.java
  api/src/test/resources/application-test.yml
  batch/src/main/java/com/garden/back/alarm/AppointmentNotifier.java
  batch/src/main/java/com/garden/back/config/ScheduleConfig.java
  batch/src/main/java/com/garden/back/region/GeoDataParser.java
  batch/src/test/java/com/garden/back/garden/OpenAPIGardenInfoClientTest.java
  batch/src/test/java/com/garden/back/region/GeoDataParserTest.java
  build.gradle
  core/src/main/java/com/garden/back/alarm/CropNotifier.java
  core/src/main/java/com/garden/back/alarm/ReportNotifier.java
  core/src/main/java/com/garden/back/appointment/domain/Appointment.java
  core/src/main/java/com/garden/back/appointment/domain/AppointmentRepository.java
  core/src/main/java/com/garden/back/appointment/service/AppointmentService.java
  core/src/main/java/com/garden/back/appointment/service/AppointmentServiceRequest.java
  core/src/main/java/com/garden/back/appointment/service/response/AppointmentResponse.java
  core/src/main/java/com/garden/back/crop/domain/CropPost.java
  core/src/main/java/com/garden/back/crop/domain/repository/CropCommandRepository.java
  core/src/main/java/com/garden/back/crop/domain/repository/CropCommandRepositoryImpl.java
  core/src/main/java/com/garden/back/crop/domain/repository/CropQueryRepositoryImpl.java
  core/src/main/java/com/garden/back/crop/service/CropCommandService.java
  core/src/main/java/com/garden/back/crop/service/CropQueryService.java
  core/src/main/java/com/garden/back/crop/service/DeleteCropPostAfterCropReportCreateEvent.java
  core/src/main/java/com/garden/back/post/domain/Post.java
  core/src/main/java/com/garden/back/post/domain/PostComment.java
  core/src/main/java/com/garden/back/post/domain/repository/PostCommandRepository.java
  core/src/main/java/com/garden/back/post/domain/repository/PostCommandRepositoryImpl.java
  core/src/main/java/com/garden/back/post/domain/repository/PostQueryRepositoryImpl.java
  core/src/main/java/com/garden/back/post/service/DeletePostAfterPostReportCreateEvent.java
  core/src/main/java/com/garden/back/post/service/PostCommandService.java
  core/src/main/java/com/garden/back/region/RegionRepository.java
  core/src/main/java/com/garden/back/report/domain/comment/CommentReport.java
  core/src/main/java/com/garden/back/report/domain/comment/CommentReportCreateEvent.java
  core/src/main/java/com/garden/back/report/domain/comment/CommentReportRepository.java
  core/src/main/java/com/garden/back/report/domain/crop/CropPostReport.java
  core/src/main/java/com/garden/back/report/domain/crop/CropPostReportCreateEvent.java
  core/src/main/java/com/garden/back/report/domain/crop/CropPostReportRepository.java
  core/src/main/java/com/garden/back/report/domain/post/PostReport.java
  core/src/main/java/com/garden/back/report/domain/post/PostReportCreateEvent.java
  core/src/main/java/com/garden/back/report/domain/post/PostReportRepository.java
  core/src/test/java/com/garden/back/appointment/domain/AppointmentTest.java
  core/src/test/java/com/garden/back/appointment/service/AppointmentServiceTest.java
  core/src/test/java/com/garden/back/crop/service/CropQueryServiceTest.java
Labels: feat

#94 feat : 채팅방 신고 기능 구현 ( 사용자 매너 점수 이벤트 처리)
  api/src/docs/asciidoc/chat/chats.adoc
  api/src/main/java/com/garden/back/chat/gardenchat/controller/GardenChatController.java
  api/src/main/java/com/garden/back/chat/gardenchat/controller/GardenChatRoomController.java
  api/src/main/java/com/garden/back/chat/gardenchat/controller/dto/request/GardenChatReportRequest.java
  api/src/main/java/com/garden/back/chat/gardenchat/controller/dto/response/GardenChatReportResponse.java
  api/src/test/java/com/garden/back/docs/chat/garden/ChatDocsTest.java
  api/src/test/java/com/garden/back/docs/chat/global/ChatRoomFixture.java
  build.gradle
  chat/src/main/java/com/garden/back/garden/domain/GardenChatImage.java
  chat/src/main/java/com/garden/back/garden/domain/GardenChatReport.java
  chat/src/main/java/com/garden/back/garden/domain/GardenChatReportImage.java
  chat/src/main/java/com/garden/back/garden/domain/GardenChatRoom.java
  chat/src/main/java/com/garden/back/garden/domain/dto/GardenChatReportDomainParam.java
  chat/src/main/java/com/garden/back/garden/domain/dto/GardenChatReportEvent.java
  chat/src/main/java/com/garden/back/garden/repository/chatreport/GardenChatReportJpaRepository.java
  chat/src/main/java/com/garden/back/garden/repository/chatreport/GardenChatReportRepository.java
  chat/src/main/java/com/garden/back/garden/repository/chatreport/GardenChatReportRepositoryImpl.java
  chat/src/main/java/com/garden/back/garden/repository/chatreport/image/GardenChatReportImageJpaRepository.java
  chat/src/main/java/com/garden/back/garden/repository/chatreport/image/GardenChatReportImageRepository.java
  chat/src/main/java/com/garden/back/garden/repository/chatreport/image/GardenChatReportImageRepositoryImpl.java
  chat/src/main/java/com/garden/back/garden/service/GardenChatRoomService.java
  chat/src/main/java/com/garden/back/garden/service/dto/request/GardenChatReportParam.java
  chat/src/main/java/com/garden/back/global/ChatReportType.java
  chat/src/main/java/com/garden/back/global/jpa/JpaConfig.java
  chat/src/test/java/com/garden/back/garden/domain/GardenChatReportTest.java
  chat/src/test/java/com/garden/back/service/ChatRoomFixture.java
  chat/src/test/java/com/garden/back/service/GardenChatRoomServiceTest.java
  core/src/main/java/com/garden/back/member/ChatReportEvent.java
  core/src/main/java/com/garden/back/member/Member.java
  core/src/main/java/com/garden/back/member/UpdateMemberMannerScoreEventHandler.java
  core/src/main/java/com/garden/back/notification/service/EmailJavaNotificationService.kt
  core/src/main/java/com/garden/back/review/CropPostReview.java
  core/src/main/java/com/garden/back/review/CropPostReviewCreateEvent.java
Labels: feat

#95 배포
  api/src/docs/asciidoc/chat/chats.adoc
  api/src/main/java/com/garden/back/chat/gardenchat/controller/GardenChatController.java
  api/src/main/java/com/garden/back/chat/gardenchat/controller/GardenChatRoomController.java
  api/src/main/java/com/garden/back/chat/gardenchat/controller/dto/request/GardenChatReportRequest.java
  api/src/main/java/com/garden/back/chat/gardenchat/controller/dto/response/GardenChatReportResponse.java
  api/src/test/java/com/garden/back/docs/chat/garden/ChatDocsTest.java
  api/src/test/java/com/garden/back/docs/chat/global/ChatRoomFixture.java
  build.gradle
  chat/src/main/java/com/garden/back/garden/domain/GardenChatImage.java
  chat/src/main/java/com/garden/back/garden/domain/GardenChatReport.java
  chat/src/main/java/com/garden/back/garden/domain/GardenChatReportImage.java
  chat/src/main/java/com/garden/back/garden/domain/GardenChatRoom.java
  chat/src/main/java/com/garden/back/garden/domain/dto/GardenChatReportDomainParam.java
  chat/src/main/java/com/garden/back/garden/domain/dto/GardenChatReportEvent.java
  chat/src/main/java/com/garden/back/garden/repository/chatreport/GardenChatReportJpaRepository.java
  chat/src/main/java/com/garden/back/garden/repository/chatreport/GardenChatReportRepository.java
  chat/src/main/java/com/garden/back/garden/repository/chatreport/GardenChatReportRepositoryImpl.java
  chat/src/main/java/com/garden/back/garden/repository/chatreport/image/GardenChatReportImageJpaRepository.java
  chat/src/main/java/com/garden/back/garden/repository/chatreport/image/GardenChatReportImageRepository.java
  chat/src/main/java/com/garden/back/garden/repository/chatreport/image/GardenChatReportImageRepositoryImpl.java
  chat/src/main/java/com/garden/back/garden/service/GardenChatRoomService.java
  chat/src/main/java/com/garden/back/garden/service/dto/request/GardenChatReportParam.java
  chat/src/main/java/com/garden/back/global/ChatReportType.java
  chat/src/main/java/com/garden/back/global/jpa/JpaConfig.java
  chat/src/test/java/com/garden/back/garden/domain/GardenChatReportTest.java
  chat/src/test/java/com/garden/back/service/ChatRoomFixture.java
  chat/src/test/java/com/garden/back/service/GardenChatRoomServiceTest.java
  core/src/main/java/com/garden/back/member/ChatReportEvent.java
  core/src/main/java/com/garden/back/member/Member.java
  core/src/main/java/com/garden/back/member/UpdateMemberMannerScoreEventHandler.java
  core/src/main/java/com/garden/back/notification/service/EmailJavaNotificationService.kt
  core/src/main/java/com/garden/back/review/CropPostReview.java
  core/src/main/java/com/garden/back/review/CropPostReviewCreateEvent.java
Labels: release
