Repository everyone-s-garden/everyonesgarden-v2, pull requests merged in 2024-02, with the labels that each got.

#107 refactor : 텃밭 상세보기 및 채팅방 목록 필드 추가
  api/src/main/java/com/garden/back/chat/gardenchat/controller/dto/response/GardenChatRoomsFindResponses.java
  api/src/main/java/com/garden/back/chat/gardenchat/facade/GardenChatRoomsFindFacadeResponses.java
  api/src/main/java/com/garden/back/garden/controller/GardenCommandController.java
  api/src/main/java/com/garden/back/garden/controller/GardenController.java
  api/src/main/java/com/garden/back/garden/controller/dto/request/GardenByComplexesRequest.java
  api/src/main/java/com/garden/back/garden/controller/dto/request/GardenByNameRequest.java
  api/src/main/java/com/garden/back/garden/controller/dto/request/GardenCreateRequest.java
  api/src/main/java/com/garden/back/garden/controller/dto/request/GardenDetailRequest.java
  api/src/main/java/com/garden/back/garden/controller/dto/request/GardenLikeCreateRequest.java
  api/src/main/java/com/garden/back/garden/controller/dto/request/GardenLikeDeleteRequest.java
  api/src/main/java/com/garden/back/garden/controller/dto/request/GardenType.java
  api/src/main/java/com/garden/back/garden/controller/dto/request/GardenUpdateRequest.java
  api/src/main/java/com/garden/back/garden/controller/dto/request/MyManagedGardenCreateRequest.java
  api/src/main/java/com/garden/back/garden/controller/dto/request/MyManagedGardenUpdateRequest.java
  api/src/main/java/com/garden/back/garden/controller/dto/request/validation/DateValidator.java
  api/src/main/java/com/garden/back/garden/controller/dto/request/validation/ValidDate.java
  api/src/main/java/com/garden/back/garden/controller/dto/response/GardenByComplexesResponses.java
  api/src/main/java/com/garden/back/garden/controller/dto/response/GardenByNameResponses.java
  api/src/main/java/com/garden/back/garden/controller/dto/response/GardenDetailResponse.java
  api/src/main/java/com/garden/back/garden/controller/dto/response/GardenGetAllResponses.java
  api/src/main/java/com/garden/back/garden/controller/dto/response/GardenLikeByMemberResponses.java
  api/src/main/java/com/garden/back/garden/controller/dto/response/GardenMineResponses.java
  api/src/main/java/com/garden/back/garden/controller/dto/response/MyManagedGardenDetailResponse.java
  api/src/main/java/com/garden/back/garden/controller/dto/response/MyManagedGardenGetResponses.java
  api/src/main/java/com/garden/back/garden/controller/dto/response/RecentGardenResponses.java
  api/src/main/java/com/garden/back/garden/dto/request/GardenDetailRequest.java
  api/src/main/java/com/garden/back/garden/dto/request/GardenType.java
  api/src/main/java/com/garden/back/garden/dto/response/GardenDetailResponse.java
  api/src/main/java/com/garden/back/garden/facade/GardenDetailFacadeRequest.java
  api/src/main/java/com/garden/back/garden/facade/GardenDetailFacadeResponse.java
  api/src/main/java/com/garden/back/garden/facade/GardenFacade.java
  api/src/test/java/com/garden/back/ControllerTestSupport.java
  api/src/test/java/com/garden/back/controller/chat/ChatRoomFacadeTest.java
  api/src/test/java/com/garden/back/controller/garden/GardenControllerTest.java
  api/src/test/java/com/garden/back/controller/garden/GardenFacadeTest.java
  api/src/test/java/com/garden/back/controller/garden/GardenFixture.java
  api/src/test/java/com/garden/back/docs/chat/garden/ChatMessageDocsTest.java
  api/src/test/java/com/garden/back/docs/chat/global/ChatRoomFixture.java
  api/src/test/java/com/garden/back/docs/garden/GardenCommandRestDocsTest.java
  api/src/test/java/com/garden/back/docs/garden/GardenFixture.java
  api/src/test/java/com/garden/back/docs/garden/GardenRestDocsTest.java
  chat/src/main/java/com/garden/back/garden/repository/chatroominfo/GardenChatRoomInfoJpaRepository.java
  chat/src/main/java/com/garden/back/garden/repository/chatroominfo/GardenChatRoomInfoRepository.java
  chat/src/main/java/com/garden/back/garden/repository/chatroominfo/GardenChatRoomInfoRepositoryImpl.java
  chat/src/main/java/com/garden/back/garden/service/GardenChatRoomService.java
  chat/src/main/java/com/garden/back/garden/service/dto/request/GardenChatRoomInfoGetParam.java
  chat/src/test/java/com/garden/back/service/ChatRoomFixture.java
  chat/src/test/java/com/garden/back/service/GardenChatRoomServiceTest.java
Labels: enhancement

#108 배포
  api/src/main/java/com/garden/back/chat/gardenchat/controller/dto/response/GardenChatRoomsFindResponses.java
  api/src/main/java/com/garden/back/chat/gardenchat/facade/GardenChatRoomsFindFacadeResponses.java
  api/src/main/java/com/garden/back/garden/controller/GardenCommandController.java
  api/src/main/java/com/garden/back/garden/controller/GardenController.java
  api/src/main/java/com/garden/back/garden/controller/dto/request/GardenByComplexesRequest.java
  api/src/main/java/com/garden/back/garden/controller/dto/request/GardenByNameRequest.java
  api/src/main/java/com/garden/back/garden/controller/dto/request/GardenCreateRequest.java
  api/src/main/java/com/garden/back/garden/controller/dto/request/GardenDetailRequest.java
  api/src/main/java/com/garden/back/garden/controller/dto/request/GardenLikeCreateRequest.java
  api/src/main/java/com/garden/back/garden/controller/dto/request/GardenLikeDeleteRequest.java
  api/src/main/java/com/garden/back/garden/controller/dto/request/GardenType.java
  api/src/main/java/com/garden/back/garden/controller/dto/request/GardenUpdateRequest.java
  api/src/main/java/com/garden/back/garden/controller/dto/request/MyManagedGardenCreateRequest.java
  api/src/main/java/com/garden/back/garden/controller/dto/request/MyManagedGardenUpdateRequest.java
  api/src/main/java/com/garden/back/garden/controller/dto/request/validation/DateValidator.java
  api/src/main/java/com/garden/back/garden/controller/dto/request/validation/ValidDate.java
  api/src/main/java/com/garden/back/garden/controller/dto/response/GardenByComplexesResponses.java
  api/src/main/java/com/garden/back/garden/controller/dto/response/GardenByNameResponses.java
  api/src/main/java/com/garden/back/garden/controller/dto/response/GardenDetailResponse.java
  api/src/main/java/com/garden/back/garden/controller/dto/response/GardenGetAllResponses.java
  api/src/main/java/com/garden/back/garden/controller/dto/response/GardenLikeByMemberResponses.java
  api/src/main/java/com/garden/back/garden/controller/dto/response/GardenMineResponses.java
  api/src/main/java/com/garden/back/garden/controller/dto/response/MyManagedGardenDetailResponse.java
  api/src/main/java/com/garden/back/garden/controller/dto/response/MyManagedGardenGetResponses.java
  api/src/main/java/com/garden/back/garden/controller/dto/response/RecentGardenResponses.java
  api/src/main/java/com/garden/back/garden/dto/request/GardenDetailRequest.java
  api/src/main/java/com/garden/back/garden/dto/request/GardenType.java
  api/src/main/java/com/garden/back/garden/dto/response/GardenDetailResponse.java
  api/src/main/java/com/garden/back/garden/facade/GardenDetailFacadeRequest.java
  api/src/main/java/com/garden/back/garden/facade/GardenDetailFacadeResponse.java
  api/src/main/java/com/garden/back/garden/facade/GardenFacade.java
  api/src/test/java/com/garden/back/ControllerTestSupport.java
  api/src/test/java/com/garden/back/controller/chat/ChatRoomFacadeTest.java
  api/src/test/java/com/garden/back/controller/garden/GardenControllerTest.java
  api/src/test/java/com/garden/back/controller/garden/GardenFacadeTest.java
  api/src/test/java/com/garden/back/controller/garden/GardenFixture.java
  api/src/test/java/com/garden/back/docs/chat/garden/ChatMessageDocsTest.java
  api/src/test/java/com/garden/back/docs/chat/global/ChatRoomFixture.java
  api/src/test/java/com/garden/back/docs/garden/GardenCommandRestDocsTest.java
  api/src/test/java/com/garden/back/docs/garden/GardenFixture.java
  api/src/test/java/com/garden/back/docs/garden/GardenRestDocsTest.java
  chat/src/main/java/com/garden/back/garden/repository/chatroominfo/GardenChatRoomInfoJpaRepository.java
  chat/src/main/java/com/garden/back/garden/repository/chatroominfo/GardenChatRoomInfoRepository.java
  chat/src/main/java/com/garden/back/garden/repository/chatroominfo/GardenChatRoomInfoRepositoryImpl.java
  chat/src/main/java/com/garden/back/garden/service/GardenChatRoomService.java
  chat/src/main/java/com/garden/back/garden/service/dto/request/GardenChatRoomInfoGetParam.java
  chat/src/test/java/com/garden/back/service/ChatRoomFixture.java
  chat/src/test/java/com/garden/back/service/GardenChatRoomServiceTest.java
Labels: release

#103 feat: 인기글 기능 추가 및 속닥속닥 게시글 타입 추가
  api/src/docs/asciidoc/post/post.adoc
  api/src/main/java/com/garden/back/post/PostController.java
  api/src/main/java/com/garden/back/post/request/FindAllPopularPostsRequest.java
  api/src/main/java/com/garden/back/post/request/FindAllPostParamRequest.java
  api/src/main/java/com/garden/back/post/request/PostCreateRequest.java
  api/src/main/java/com/garden/back/post/request/PostUpdateRequest.java
  api/src/test/java/com/garden/back/controller/post/PostControllerTest.java
  api/src/test/java/com/garden/back/docs/post/PostRestDocsTest.java
  core/src/main/java/com/garden/back/post/domain/Post.java
  core/src/main/java/com/garden/back/post/domain/PostType.java
  core/src/main/java/com/garden/back/post/domain/repository/PostCommandRepositoryImpl.java
  core/src/main/java/com/garden/back/post/domain/repository/PostQueryRepository.java
  core/src/main/java/com/garden/back/post/domain/repository/PostQueryRepositoryImpl.java
  core/src/main/java/com/garden/back/post/domain/repository/request/FindAllPopularRepositoryPostsRequest.java
  core/src/main/java/com/garden/back/post/domain/repository/request/FindAllPostParamRepositoryRequest.java
  core/src/main/java/com/garden/back/post/domain/repository/request/PostUpdateRepositoryRequest.java
  core/src/main/java/com/garden/back/post/domain/repository/response/FindAllPopularPostsResponse.java
  core/src/main/java/com/garden/back/post/service/PostQueryService.java
  core/src/main/java/com/garden/back/post/service/request/PostCreateServiceRequest.java
  core/src/main/java/com/garden/back/post/service/request/PostUpdateServiceRequest.java
  core/src/test/java/com/garden/back/post/domain/PostTest.java
  core/src/test/java/com/garden/back/post/service/PostCommandServiceTest.java
  core/src/test/java/com/garden/back/post/service/PostQueryServiceTest.java
  core/src/test/java/com/garden/back/report/service/ReportServiceTest.java
Labels: feat

#112 refactor : 채팅 세션 Id 얻기
  api/build.gradle
  api/src/docs/asciidoc/chat/chats.adoc
  api/src/main/java/com/garden/back/auth/config/SecurityConfig.java
  api/src/main/java/com/garden/back/auth/jwt/JwtAuthenticationFilter.java
  api/src/main/java/com/garden/back/chat/event/WebSocketListenerConfig.java
  api/src/main/java/com/garden/back/chat/gardenchat/controller/GardenChatController.java
  api/src/main/java/com/garden/back/chat/gardenchat/controller/GardenChatRoomController.java
  api/src/main/java/com/garden/back/chat/gardenchat/controller/dto/request/GardenMessageSendRequest.java
  api/src/main/java/com/garden/back/chat/handler/ChatPreHandler.java
  api/src/main/java/com/garden/back/global/SocketConfig.java
  api/src/test/java/com/garden/back/docs/chat/garden/ChatDocsTest.java
  chat/src/main/java/com/garden/back/garden/repository/chatentry/garden/GardenChatRoomEntryRepositoryImpl.java
  chat/src/main/java/com/garden/back/garden/repository/chatentry/garden/GardenChatRoomRoomEntryLocalRepository.java
  chat/src/main/java/com/garden/back/garden/repository/websocketinfo/WebSocketInfo.java
  chat/src/main/java/com/garden/back/garden/repository/websocketinfo/WebSocketInfoLocalRepository.java
  chat/src/main/java/com/garden/back/garden/repository/websocketinfo/WebSocketInfoRepository.java
  chat/src/main/java/com/garden/back/garden/repository/websocketinfo/WebSocketInfoRepositoryImpl.java
  chat/src/main/java/com/garden/back/garden/service/GardenChatService.java
  chat/src/test/java/com/garden/back/service/GardenChatServiceTest.java
Labels: enhancement

#117 refactor: 채팅방 관련 필드 추가 및 수정
  api/src/main/java/com/garden/back/chat/gardenchat/controller/dto/response/GardenChatRoomEnterResponse.java
  api/src/main/java/com/garden/back/chat/gardenchat/controller/dto/response/GardenMessageSendResponse.java
  api/src/main/java/com/garden/back/chat/gardenchat/facade/ChatRoomFacade.java
  api/src/main/java/com/garden/back/chat/gardenchat/facade/GardenChatRoomEnterFacadeResponse.java
  api/src/test/java/com/garden/back/controller/chat/ChatRoomFacadeTest.java
  api/src/test/java/com/garden/back/docs/chat/garden/ChatDocsTest.java
  api/src/test/java/com/garden/back/docs/chat/global/ChatRoomFixture.java
Labels: enhancement

#119 refactor: 날씨 데이터 응답 필드 추가
  api/src/docs/asciidoc/weather/weathers.adoc
  api/src/test/java/com/garden/back/docs/weather/WeatherRestDocsTest.java
  core/src/main/java/com/garden/back/weather/infra/api/open/response/MidWeatherResponse.java
  core/src/main/java/com/garden/back/weather/infra/response/WeatherPerHourAndTomorrowInfo.java
  core/src/main/java/com/garden/back/weather/infra/response/WeekWeatherInfo.java
  core/src/main/java/com/garden/back/weather/service/response/WeekWeatherApiResponse.java
  core/src/test/java/com/garden/back/weather/infra/api/open/OpenAPIAndNaverWeatherFetcherTest.java
Labels: feat

#123 refactor: 게시글 조회 누락 필드 추가
  api/src/docs/asciidoc/mypage/mypage.adoc
  api/src/main/java/com/garden/back/member/MemberController.java
  api/src/main/java/com/garden/back/post/PostController.java
  api/src/test/java/com/garden/back/docs/member/MemberRestDocsTest.java
  api/src/test/java/com/garden/back/docs/post/PostRestDocsTest.java
  core/src/main/java/com/garden/back/member/repository/MemberRepository.java
  core/src/main/java/com/garden/back/member/repository/response/MemberInfoResponse.java
  core/src/main/java/com/garden/back/member/service/MemberService.java
  core/src/main/java/com/garden/back/post/domain/repository/PostQueryRepository.java
  core/src/main/java/com/garden/back/post/domain/repository/PostQueryRepositoryImpl.java
  core/src/main/java/com/garden/back/post/domain/repository/response/FindAllPostsResponse.java
  core/src/main/java/com/garden/back/post/domain/repository/response/FindPostDetailsResponse.java
  core/src/main/java/com/garden/back/post/domain/repository/response/FindPostsAllCommentResponse.java
  core/src/main/java/com/garden/back/post/service/PostQueryService.java
  core/src/test/java/com/garden/back/member/service/MemberServiceTest.java
  core/src/test/java/com/garden/back/post/service/PostQueryServiceTest.java
Labels: refactor

#125 refactor: 속닥속닥 api 응답 필드 수정, query dsl 서브쿼리 limit 제거 버그 해결
  api/src/test/java/com/garden/back/docs/post/PostRestDocsTest.java
  core/src/main/java/com/garden/back/post/domain/repository/PostQueryRepositoryImpl.java
  core/src/main/java/com/garden/back/post/domain/repository/response/FindAllPopularPostsResponse.java
  core/src/main/java/com/garden/back/post/domain/repository/response/FindPostDetailsResponse.java
  core/src/main/java/com/garden/back/post/domain/repository/response/FindPostsAllCommentResponse.java
  core/src/test/java/com/garden/back/post/service/PostQueryServiceTest.java
Labels: feat

#127 dcos: 나의 지역 api 문서 추가
  api/src/docs/asciidoc/index.asciidoc
Labels: documentation

#132 Refactor/garden : 텃밭 관련 위도 경도 추가 등
  api/src/docs/asciidoc/garden/gardens.adoc
  api/src/main/java/com/garden/back/garden/controller/GardenController.java
  api/src/main/java/com/garden/back/garden/controller/dto/response/GardenLocationResponse.java
  api/src/main/java/com/garden/back/garden/controller/dto/response/RecentCreatedGardenResponses.java
  api/src/main/java/com/garden/back/garden/controller/dto/response/RecentGardenResponses.java
  api/src/test/java/com/garden/back/controller/garden/GardenControllerTest.java
  api/src/test/java/com/garden/back/docs/garden/GardenFixture.java
  api/src/test/java/com/garden/back/docs/garden/GardenRestDocsTest.java
  core/src/main/java/com/garden/back/garden/repository/garden/GardenJpaRepository.java
  core/src/main/java/com/garden/back/garden/repository/garden/GardenRepository.java
  core/src/main/java/com/garden/back/garden/repository/garden/GardenRepositoryImpl.java
  core/src/main/java/com/garden/back/garden/repository/garden/dto/response/GardenLocationRepositoryResponse.java
  core/src/main/java/com/garden/back/garden/repository/garden/dto/response/RecentCreateGardenRepositoryResponse.java
  core/src/main/java/com/garden/back/garden/repository/gardenlike/GardenLikeJpaRepository.java
  core/src/main/java/com/garden/back/garden/repository/gardenlike/GardenLikeRepository.java
  core/src/main/java/com/garden/back/garden/repository/gardenlike/GardenLikeRepositoryImpl.java
  core/src/main/java/com/garden/back/garden/service/GardenCommandService.java
  core/src/main/java/com/garden/back/garden/service/GardenReadService.java
  core/src/main/java/com/garden/back/garden/service/dto/response/GardenLocationResult.java
  core/src/main/java/com/garden/back/garden/service/dto/response/RecentCreatedGardenResults.java
  core/src/main/java/com/garden/back/garden/service/dto/response/RecentGardenResults.java
  core/src/main/java/com/garden/back/garden/service/recentview/RecentViewGarden.java
  core/src/test/java/com/garden/back/garden/service/GardenCommandServiceTest.java
  core/src/test/java/com/garden/back/garden/service/GardenReadServiceTest.java
  core/src/test/java/com/garden/back/garden/service/recentview/RecentViewGardensTest.java
  core/src/test/java/com/garden/back/testutil/garden/GardenFixture.java
Labels: feat, refactor

#136 refactor : 내가 가꾸는 텃밭 세부사항 필드 추가
  api/src/main/java/com/garden/back/garden/controller/GardenCommandController.java
  api/src/main/java/com/garden/back/garden/controller/dto/request/GardenCreateRequest.java
  api/src/main/java/com/garden/back/garden/controller/dto/request/GardenUpdateRequest.java
  api/src/main/java/com/garden/back/garden/controller/dto/request/MyManagedGardenCreateRequest.java
  api/src/main/java/com/garden/back/garden/controller/dto/request/MyManagedGardenUpdateRequest.java
  api/src/main/java/com/garden/back/garden/controller/dto/response/GardenDetailResponse.java
  api/src/main/java/com/garden/back/garden/controller/dto/response/MyManagedGardenDetailResponse.java
  api/src/main/java/com/garden/back/garden/controller/dto/response/MyManagedGardenGetResponses.java
  api/src/main/java/com/garden/back/garden/facade/GardenDetailFacadeResponse.java
  api/src/test/java/com/garden/back/controller/chat/ChatRoomFixture.java
  api/src/test/java/com/garden/back/controller/garden/GardenControllerTest.java
  api/src/test/java/com/garden/back/controller/garden/GardenFacadeTest.java
  api/src/test/java/com/garden/back/controller/garden/GardenFixture.java
  api/src/test/java/com/garden/back/docs/garden/GardenCommandRestDocsTest.java
  api/src/test/java/com/garden/back/docs/garden/GardenFixture.java
  api/src/test/java/com/garden/back/docs/garden/GardenRestDocsTest.java
  core/src/main/java/com/garden/back/garden/domain/Garden.java
  core/src/main/java/com/garden/back/garden/domain/MyManagedGarden.java
  core/src/main/java/com/garden/back/garden/domain/dto/GardenUpdateDomainRequest.java
  core/src/main/java/com/garden/back/garden/domain/dto/MyManagedGardenCreateDomainRequest.java
  core/src/main/java/com/garden/back/garden/domain/dto/MyManagedGardenUpdateDomainRequest.java
  core/src/main/java/com/garden/back/garden/repository/garden/GardenJpaRepository.java
  core/src/main/java/com/garden/back/garden/repository/garden/dto/response/GardenDetailRepositoryResponse.java
  core/src/main/java/com/garden/back/garden/repository/garden/entity/GardenEntity.java
  core/src/main/java/com/garden/back/garden/repository/mymanagedgarden/MyManagedGardenJpaRepository.java
  core/src/main/java/com/garden/back/garden/repository/mymanagedgarden/dto/MyManagedGardenDetailRepositoryResponse.java
  core/src/main/java/com/garden/back/garden/repository/mymanagedgarden/dto/MyManagedGardensGetRepositoryResponse.java
  core/src/main/java/com/garden/back/garden/repository/mymanagedgarden/entity/MyManagedGardenEntity.java
  core/src/main/java/com/garden/back/garden/service/GardenCommandService.java
  core/src/main/java/com/garden/back/garden/service/dto/request/GardenCreateParam.java
  core/src/main/java/com/garden/back/garden/service/dto/request/GardenUpdateParam.java
  core/src/main/java/com/garden/back/garden/service/dto/request/MyManagedGardenCreateParam.java
  core/src/main/java/com/garden/back/garden/service/dto/request/MyManagedGardenUpdateParam.java
  core/src/main/java/com/garden/back/garden/service/dto/response/GardenDetailResult.java
  core/src/main/java/com/garden/back/garden/service/dto/response/MyManagedGardenDetailResult.java
  core/src/main/java/com/garden/back/garden/service/dto/response/MyManagedGardenGetResults.java
  core/src/test/java/com/garden/back/garden/domain/GardenTest.java
  core/src/test/java/com/garden/back/garden/domain/MyManagedGardenTest.java
  core/src/test/java/com/garden/back/garden/service/GardenCommandServiceTest.java
  core/src/test/java/com/garden/back/garden/service/GardenReadServiceTest.java
  core/src/test/java/com/garden/back/testutil/garden/GardenFixture.java
Labels: enhancement

#138 release
  api/src/main/java/com/garden/back/garden/controller/GardenCommandController.java
  api/src/main/java/com/garden/back/garden/controller/dto/request/GardenCreateRequest.java
  api/src/main/java/com/garden/back/garden/controller/dto/request/GardenUpdateRequest.java
  api/src/main/java/com/garden/back/garden/controller/dto/request/MyManagedGardenCreateRequest.java
  api/src/main/java/com/garden/back/garden/controller/dto/request/MyManagedGardenUpdateRequest.java
  api/src/main/java/com/garden/back/garden/controller/dto/response/GardenDetailResponse.java
  api/src/main/java/com/garden/back/garden/controller/dto/response/MyManagedGardenDetailResponse.java
  api/src/main/java/com/garden/back/garden/controller/dto/response/MyManagedGardenGetResponses.java
  api/src/main/java/com/garden/back/garden/facade/GardenDetailFacadeResponse.java
  api/src/test/java/com/garden/back/controller/chat/ChatRoomFixture.java
  api/src/test/java/com/garden/back/controller/garden/GardenControllerTest.java
  api/src/test/java/com/garden/back/controller/garden/GardenFacadeTest.java
  api/src/test/java/com/garden/back/controller/garden/GardenFixture.java
  api/src/test/java/com/garden/back/docs/garden/GardenCommandRestDocsTest.java
  api/src/test/java/com/garden/back/docs/garden/GardenFixture.java
  api/src/test/java/com/garden/back/docs/garden/GardenRestDocsTest.java
  core/src/main/java/com/garden/back/garden/domain/Garden.java
  core/src/main/java/com/garden/back/garden/domain/MyManagedGarden.java
  core/src/main/java/com/garden/back/garden/domain/dto/GardenUpdateDomainRequest.java
  core/src/main/java/com/garden/back/garden/domain/dto/MyManagedGardenCreateDomainRequest.java
  core/src/main/java/com/garden/back/garden/domain/dto/MyManagedGardenUpdateDomainRequest.java
  core/src/main/java/com/garden/back/garden/repository/garden/GardenJpaRepository.java
  core/src/main/java/com/garden/back/garden/repository/garden/dto/response/GardenDetailRepositoryResponse.java
  core/src/main/java/com/garden/back/garden/repository/garden/entity/GardenEntity.java
  core/src/main/java/com/garden/back/garden/repository/mymanagedgarden/MyManagedGardenJpaRepository.java
  core/src/main/java/com/garden/back/garden/repository/mymanagedgarden/dto/MyManagedGardenDetailRepositoryResponse.java
  core/src/main/java/com/garden/back/garden/repository/mymanagedgarden/dto/MyManagedGardensGetRepositoryResponse.java
  core/src/main/java/com/garden/back/garden/repository/mymanagedgarden/entity/MyManagedGardenEntity.java
  core/src/main/java/com/garden/back/garden/service/GardenCommandService.java
  core/src/main/java/com/garden/back/garden/service/dto/request/GardenCreateParam.java
  core/src/main/java/com/garden/back/garden/service/dto/request/GardenUpdateParam.java
  core/src/main/java/com/garden/back/garden/service/dto/request/MyManagedGardenCreateParam.java
  core/src/main/java/com/garden/back/garden/service/dto/request/MyManagedGardenUpdateParam.java
  core/src/main/java/com/garden/back/garden/service/dto/response/GardenDetailResult.java
  core/src/main/java/com/garden/back/garden/service/dto/response/MyManagedGardenDetailResult.java
  core/src/main/java/com/garden/back/garden/service/dto/response/MyManagedGardenGetResults.java
  core/src/test/java/com/garden/back/garden/domain/GardenTest.java
  core/src/test/java/com/garden/back/garden/domain/MyManagedGardenTest.java
  core/src/test/java/com/garden/back/garden/service/GardenCommandServiceTest.java
  core/src/test/java/com/garden/back/garden/service/GardenReadServiceTest.java
  core/src/test/java/com/garden/back/testutil/garden/GardenFixture.java
Labels: enhancement

#139 refactor: 게시글 유저 정보 응답 필드 추가
  .kotlin/sessions/kotlin-compiler-5521878765121192467.salive
  api/src/test/java/com/garden/back/docs/post/PostRestDocsTest.java
  core/src/main/java/com/garden/back/crop/infra/wiki/MonthlyWikiRecommendedCropsRepository.java
  core/src/main/java/com/garden/back/post/domain/repository/PostQueryRepositoryImpl.java
  core/src/main/java/com/garden/back/post/domain/repository/response/FindAllPopularPostsResponse.java
  core/src/main/java/com/garden/back/post/domain/repository/response/FindAllPostsResponse.java
  core/src/main/java/com/garden/back/post/domain/repository/response/FindPostDetailsResponse.java
  core/src/main/java/com/garden/back/post/domain/repository/response/FindPostsAllCommentResponse.java
  core/src/main/java/com/garden/back/post/domain/repository/response/UserResponse.java
  core/src/test/java/com/garden/back/post/service/PostQueryServiceTest.java
Labels: refactor

#140 release
  .kotlin/sessions/kotlin-compiler-5521878765121192467.salive
  api/src/test/java/com/garden/back/docs/post/PostRestDocsTest.java
  core/src/main/java/com/garden/back/crop/infra/wiki/MonthlyWikiRecommendedCropsRepository.java
  core/src/main/java/com/garden/back/post/domain/repository/PostQueryRepositoryImpl.java
  core/src/main/java/com/garden/back/post/domain/repository/response/FindAllPopularPostsResponse.java
  core/src/main/java/com/garden/back/post/domain/repository/response/FindAllPostsResponse.java
  core/src/main/java/com/garden/back/post/domain/repository/response/FindPostDetailsResponse.java
  core/src/main/java/com/garden/back/post/domain/repository/response/FindPostsAllCommentResponse.java
  core/src/main/java/com/garden/back/post/domain/repository/response/UserResponse.java
  core/src/test/java/com/garden/back/post/service/PostQueryServiceTest.java
Labels: release

#142 feat : 클라이언트 요청에 따라 내가 가꾸는 텃밭 필드 빈 값 저장 수정
  api/src/main/java/com/garden/back/chat/event/WebSocketEventHandler.java
  core/src/main/java/com/garden/back/garden/domain/MyManagedGarden.java
Labels: refactor
